/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.dubbo.common.dao;

import com.dubbo.common.dao.NeteaseNewsExample;
import com.dubbo.common.model.NeteaseNews;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeteaseNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int countByExample(NeteaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int deleteByExample(NeteaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int insert(NeteaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int insertSelective(NeteaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    List<NeteaseNews> selectByExample(NeteaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    NeteaseNews selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NeteaseNews record, @Param("example") NeteaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NeteaseNews record, @Param("example") NeteaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NeteaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NeteaseNews record);
}