/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.dubbo.common.model;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;
import java.util.Date;

/**
* NeteaseNews设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class NeteaseNews implements Serializable {
    /**
     * t_netease_news.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * t_netease_news.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * 新闻类型 娱乐类   体育类  军事类
     * t_netease_news.news_type
     *
     * @mbggenerated
     */
    private String newsType;

    /**
     * t_netease_news.has_img
     *
     * @mbggenerated
     */
    private String hasImg;

    /**
     * t_netease_news.digest
     *
     * @mbggenerated
     */
    private String digest;

    /**
     * t_netease_news.comment_count
     *
     * @mbggenerated
     */
    private Long commentCount;

    /**
     * t_netease_news.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * t_netease_news.doc_id
     *
     * @mbggenerated
     */
    private String docId;

    /**
     * t_netease_news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * t_netease_news.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * t_netease_news.priority
     *
     * @mbggenerated
     */
    private Long priority;

    /**
     * t_netease_news.live_info
     *
     * @mbggenerated
     */
    private String liveInfo;

    /**
     * t_netease_news.img_src
     *
     * @mbggenerated
     */
    private String imgSrc;

    /**
     * t_netease_news.stitle
     *
     * @mbggenerated
     */
    private String stitle;

    /**
     * t_netease_news.ptime
     *
     * @mbggenerated
     */
    private String ptime;

    /**
     * t_netease_news.img_src_3g_type
     *
     * @mbggenerated
     */
    private String imgSrc3gType;

    /**
     * t_netease_news.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column t_netease_news.id
     *
     * @return the value of t_netease_news.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets the value of the database column t_netease_news.id
     *
     * @param id the value for t_netease_news.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column t_netease_news.uuid
     *
     * @return the value of t_netease_news.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method sets the value of the database column t_netease_news.uuid
     *
     * @param uuid the value for t_netease_news.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * 新闻类型 娱乐类   体育类  军事类
     * This method returns the value of the database column t_netease_news.news_type
     *
     * @return the value of t_netease_news.news_type
     *
     * @mbggenerated
     */
    public String getNewsType() {
        return newsType;
    }

    /**
     * 新闻类型 娱乐类   体育类  军事类
     * This method sets the value of the database column t_netease_news.news_type
     *
     * @param newsType the value for t_netease_news.news_type
     *
     * @mbggenerated
     */
    public void setNewsType(String newsType) {
        this.newsType = newsType;
    }

    /**
     * This method returns the value of the database column t_netease_news.has_img
     *
     * @return the value of t_netease_news.has_img
     *
     * @mbggenerated
     */
    public String getHasImg() {
        return hasImg;
    }

    /**
     * This method sets the value of the database column t_netease_news.has_img
     *
     * @param hasImg the value for t_netease_news.has_img
     *
     * @mbggenerated
     */
    public void setHasImg(String hasImg) {
        this.hasImg = hasImg;
    }

    /**
     * This method returns the value of the database column t_netease_news.digest
     *
     * @return the value of t_netease_news.digest
     *
     * @mbggenerated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method sets the value of the database column t_netease_news.digest
     *
     * @param digest the value for t_netease_news.digest
     *
     * @mbggenerated
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * This method returns the value of the database column t_netease_news.comment_count
     *
     * @return the value of t_netease_news.comment_count
     *
     * @mbggenerated
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method sets the value of the database column t_netease_news.comment_count
     *
     * @param commentCount the value for t_netease_news.comment_count
     *
     * @mbggenerated
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method returns the value of the database column t_netease_news.url
     *
     * @return the value of t_netease_news.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method sets the value of the database column t_netease_news.url
     *
     * @param url the value for t_netease_news.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method returns the value of the database column t_netease_news.doc_id
     *
     * @return the value of t_netease_news.doc_id
     *
     * @mbggenerated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method sets the value of the database column t_netease_news.doc_id
     *
     * @param docId the value for t_netease_news.doc_id
     *
     * @mbggenerated
     */
    public void setDocId(String docId) {
        this.docId = docId;
    }

    /**
     * This method returns the value of the database column t_netease_news.title
     *
     * @return the value of t_netease_news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method sets the value of the database column t_netease_news.title
     *
     * @param title the value for t_netease_news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method returns the value of the database column t_netease_news.source
     *
     * @return the value of t_netease_news.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method sets the value of the database column t_netease_news.source
     *
     * @param source the value for t_netease_news.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method returns the value of the database column t_netease_news.priority
     *
     * @return the value of t_netease_news.priority
     *
     * @mbggenerated
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method sets the value of the database column t_netease_news.priority
     *
     * @param priority the value for t_netease_news.priority
     *
     * @mbggenerated
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method returns the value of the database column t_netease_news.live_info
     *
     * @return the value of t_netease_news.live_info
     *
     * @mbggenerated
     */
    public String getLiveInfo() {
        return liveInfo;
    }

    /**
     * This method sets the value of the database column t_netease_news.live_info
     *
     * @param liveInfo the value for t_netease_news.live_info
     *
     * @mbggenerated
     */
    public void setLiveInfo(String liveInfo) {
        this.liveInfo = liveInfo;
    }

    /**
     * This method returns the value of the database column t_netease_news.img_src
     *
     * @return the value of t_netease_news.img_src
     *
     * @mbggenerated
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method sets the value of the database column t_netease_news.img_src
     *
     * @param imgSrc the value for t_netease_news.img_src
     *
     * @mbggenerated
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc;
    }

    /**
     * This method returns the value of the database column t_netease_news.stitle
     *
     * @return the value of t_netease_news.stitle
     *
     * @mbggenerated
     */
    public String getStitle() {
        return stitle;
    }

    /**
     * This method sets the value of the database column t_netease_news.stitle
     *
     * @param stitle the value for t_netease_news.stitle
     *
     * @mbggenerated
     */
    public void setStitle(String stitle) {
        this.stitle = stitle;
    }

    /**
     * This method returns the value of the database column t_netease_news.ptime
     *
     * @return the value of t_netease_news.ptime
     *
     * @mbggenerated
     */
    public String getPtime() {
        return ptime;
    }

    /**
     * This method sets the value of the database column t_netease_news.ptime
     *
     * @param ptime the value for t_netease_news.ptime
     *
     * @mbggenerated
     */
    public void setPtime(String ptime) {
        this.ptime = ptime;
    }

    /**
     * This method returns the value of the database column t_netease_news.img_src_3g_type
     *
     * @return the value of t_netease_news.img_src_3g_type
     *
     * @mbggenerated
     */
    public String getImgSrc3gType() {
        return imgSrc3gType;
    }

    /**
     * This method sets the value of the database column t_netease_news.img_src_3g_type
     *
     * @param imgSrc3gType the value for t_netease_news.img_src_3g_type
     *
     * @mbggenerated
     */
    public void setImgSrc3gType(String imgSrc3gType) {
        this.imgSrc3gType = imgSrc3gType;
    }

    /**
     * This method returns the value of the database column t_netease_news.create_time
     *
     * @return the value of t_netease_news.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method sets the value of the database column t_netease_news.create_time
     *
     * @param createTime the value for t_netease_news.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NeteaseNews other = (NeteaseNews) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getNewsType() == null ? other.getNewsType() == null : this.getNewsType().equals(other.getNewsType()))
            && (this.getHasImg() == null ? other.getHasImg() == null : this.getHasImg().equals(other.getHasImg()))
            && (this.getDigest() == null ? other.getDigest() == null : this.getDigest().equals(other.getDigest()))
            && (this.getCommentCount() == null ? other.getCommentCount() == null : this.getCommentCount().equals(other.getCommentCount()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getDocId() == null ? other.getDocId() == null : this.getDocId().equals(other.getDocId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getLiveInfo() == null ? other.getLiveInfo() == null : this.getLiveInfo().equals(other.getLiveInfo()))
            && (this.getImgSrc() == null ? other.getImgSrc() == null : this.getImgSrc().equals(other.getImgSrc()))
            && (this.getStitle() == null ? other.getStitle() == null : this.getStitle().equals(other.getStitle()))
            && (this.getPtime() == null ? other.getPtime() == null : this.getPtime().equals(other.getPtime()))
            && (this.getImgSrc3gType() == null ? other.getImgSrc3gType() == null : this.getImgSrc3gType().equals(other.getImgSrc3gType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getNewsType() == null) ? 0 : getNewsType().hashCode());
        result = prime * result + ((getHasImg() == null) ? 0 : getHasImg().hashCode());
        result = prime * result + ((getDigest() == null) ? 0 : getDigest().hashCode());
        result = prime * result + ((getCommentCount() == null) ? 0 : getCommentCount().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getDocId() == null) ? 0 : getDocId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getLiveInfo() == null) ? 0 : getLiveInfo().hashCode());
        result = prime * result + ((getImgSrc() == null) ? 0 : getImgSrc().hashCode());
        result = prime * result + ((getStitle() == null) ? 0 : getStitle().hashCode());
        result = prime * result + ((getPtime() == null) ? 0 : getPtime().hashCode());
        result = prime * result + ((getImgSrc3gType() == null) ? 0 : getImgSrc3gType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_netease_news
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", newsType=").append(newsType);
        sb.append(", hasImg=").append(hasImg);
        sb.append(", digest=").append(digest);
        sb.append(", commentCount=").append(commentCount);
        sb.append(", url=").append(url);
        sb.append(", docId=").append(docId);
        sb.append(", title=").append(title);
        sb.append(", source=").append(source);
        sb.append(", priority=").append(priority);
        sb.append(", liveInfo=").append(liveInfo);
        sb.append(", imgSrc=").append(imgSrc);
        sb.append(", stitle=").append(stitle);
        sb.append(", ptime=").append(ptime);
        sb.append(", imgSrc3gType=").append(imgSrc3gType);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}